;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-star
        comment-region
        end-of-buffer
        indent-for-tab-command
        kill-region
        matlab-electric-comment
        matlab-linefeed
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-yank
        python-indent-electric-colon
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        buffer-menu
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        find-file
        find-tag
        goto-line
        handle-switch-frame
        magit-status
        mouse-set-region
        previous-buffer
        ))
